# Generated by Django 5.2.13 on 2026-04-23 06:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='닉네임')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='나이')),
                ('assets', models.BigIntegerField(blank=True, null=True, verbose_name='자산 (원)')),
                ('salary', models.BigIntegerField(blank=True, null=True, verbose_name='연봉 (원)')),
                ('investment_style', models.CharField(choices=[('aggressive', '공격 투자형'), ('growth', '성장 추구형'), ('balanced', '위험 중립형'), ('stable', '안정 추구형'), ('conservative', '안정형')], default='balanced', max_length=20, verbose_name='투자 성향')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='프로필 사진')),
                ('bio', models.TextField(blank=True, verbose_name='자기소개')),
                ('favorite_bank', models.CharField(blank=True, max_length=50, verbose_name='최애 은행')),
                ('saving_style', models.CharField(choices=[('short', '단기 (1년 미만)'), ('mid', '중기 (1~3년)'), ('long', '장기 (3년 이상)')], default='mid', max_length=10, verbose_name='저축 성향')),
                ('interest_stocks', models.CharField(blank=True, max_length=200, verbose_name='관심 종목')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자 목록',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
