# Generated by Django 5.2.13 on 2026-04-23 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.CharField(max_length=20, verbose_name='금융회사 코드')),
                ('kor_co_nm', models.CharField(max_length=100, verbose_name='금융회사명')),
                ('fin_prdt_cd', models.CharField(max_length=50, unique=True, verbose_name='상품 코드')),
                ('fin_prdt_nm', models.CharField(max_length=200, verbose_name='상품명')),
                ('join_way', models.CharField(blank=True, max_length=100, verbose_name='가입 방법')),
                ('join_deny', models.IntegerField(default=1, verbose_name='가입 제한')),
                ('join_member', models.TextField(blank=True, verbose_name='가입 대상')),
                ('spcl_cnd', models.TextField(blank=True, verbose_name='우대 조건')),
                ('etc_note', models.TextField(blank=True, verbose_name='기타 유의사항')),
                ('max_limit', models.BigIntegerField(blank=True, null=True, verbose_name='최고 한도')),
                ('dcls_month', models.CharField(blank=True, max_length=8, verbose_name='공시 월')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '정기예금 상품',
                'verbose_name_plural': '정기예금 상품 목록',
                'ordering': ['kor_co_nm', 'fin_prdt_nm'],
            },
        ),
        migrations.CreateModel(
            name='DepositOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=50)),
                ('intr_rate_type_nm', models.CharField(blank=True, max_length=20, verbose_name='금리 유형')),
                ('save_trm', models.IntegerField(verbose_name='저축 기간 (개월)')),
                ('intr_rate', models.FloatField(blank=True, null=True, verbose_name='기본 금리 (%)')),
                ('intr_rate2', models.FloatField(blank=True, null=True, verbose_name='최고 우대 금리 (%)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.depositproduct')),
            ],
            options={
                'verbose_name': '예금 옵션',
                'verbose_name_plural': '예금 옵션 목록',
                'ordering': ['save_trm'],
            },
        ),
    ]
